import type { Incident, Vehicle } from "@workspace/api-zod";

export type DataSourceKind = "LIVE" | "PUBLIC" | "GOVERNMENT" | "FIELD" | "SIMULATED";

export const simulatedSource = {
  kind: "SIMULATED" as const,
  label: "Seeded demonstration data",
  updatedAt: new Date().toISOString(),
};

export const vehicles: Vehicle[] = [
  {
    id: "veh-001",
    registration: "AS-01-TR-4821",
    driver: "R. Das",
    cargo: "Essential medicines",
    cargoPriority: "critical",
    route: "Guwahati → Kohima",
    status: "moving",
    eta: "Today, 18:40",
    lat: 25.941,
    lng: 93.725,
    riskScore: 0.18,
    lastSeen: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    source: simulatedSource,
  },
  {
    id: "veh-002",
    registration: "ML-05-B-1190",
    driver: "P. Khonglah",
    cargo: "Infant nutrition kits",
    cargoPriority: "essential",
    route: "Shillong → Aizawl",
    status: "delayed",
    eta: "Tomorrow, 07:15",
    lat: 25.5788,
    lng: 91.8933,
    riskScore: 0.64,
    lastSeen: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    source: simulatedSource,
  },
  {
    id: "veh-003",
    registration: "MZ-01-C-7008",
    driver: "L. Lalhmingmawia",
    cargo: "Water purification units",
    cargoPriority: "essential",
    route: "Silchar → Aizawl",
    status: "moving",
    eta: "Today, 21:05",
    lat: 24.817,
    lng: 92.7979,
    riskScore: 0.39,
    lastSeen: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    source: simulatedSource,
  },
  {
    id: "veh-004",
    registration: "AR-03-D-3055",
    driver: "T. Taba",
    cargo: "Relief food grains",
    cargoPriority: "standard",
    route: "Dibrugarh → Itanagar",
    status: "idle",
    eta: "Tomorrow, 12:30",
    lat: 27.0844,
    lng: 93.6053,
    riskScore: 0.27,
    lastSeen: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    source: simulatedSource,
  },
  {
    id: "veh-005",
    registration: "TR-01-E-9084",
    driver: "S. Debbarma",
    cargo: "Emergency shelter kits",
    cargoPriority: "critical",
    route: "Agartala → Aizawl",
    status: "offline",
    eta: "Location pending",
    lat: 23.8315,
    lng: 91.2868,
    riskScore: 0.82,
    lastSeen: new Date(Date.now() - 42 * 60 * 1000).toISOString(),
    source: simulatedSource,
  },
];

export const incidents: Incident[] = [
  {
    id: "inc-001",
    title: "Landslide risk near Peren bend",
    type: "landslide",
    severity: "critical",
    location: "NH-29, Peren district",
    lat: 25.512,
    lng: 93.737,
    reportedBy: "Field unit N-14",
    reportedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    status: "verifying",
    description: "Fresh debris on the westbound shoulder with active slope movement after overnight rain.",
    source: { ...simulatedSource, kind: "FIELD", label: "Seeded field report" },
  },
  {
    id: "inc-002",
    title: "Road surface damage",
    type: "road_damage",
    severity: "high",
    location: "Aizawl–Silchar road, Dholai",
    lat: 24.678,
    lng: 92.752,
    reportedBy: "Field unit M-08",
    reportedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: "open",
    description: "Two-lane section reduced to one lane. Heavy vehicles should reduce speed.",
    source: { ...simulatedSource, kind: "FIELD", label: "Seeded field report" },
  },
  {
    id: "inc-003",
    title: "Bridge inspection in progress",
    type: "bridge",
    severity: "medium",
    location: "Jia Bharali bridge, Sonitpur",
    lat: 26.724,
    lng: 92.849,
    reportedBy: "District control room",
    reportedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: "verifying",
    description: "Routine inspection has slowed traffic in both directions for approximately 20 minutes.",
    source: { ...simulatedSource, kind: "GOVERNMENT", label: "Seeded control-room report" },
  },
  {
    id: "inc-004",
    title: "Flash flood watch",
    type: "flood",
    severity: "high",
    location: "Barak valley low crossings",
    lat: 24.833,
    lng: 92.778,
    reportedBy: "Weather provider adapter",
    reportedAt: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    status: "open",
    description: "Water levels are rising near two low crossings. Route recommendations now apply a risk penalty.",
    source: simulatedSource,
  },
];

export function dataSource(kind: DataSourceKind, label: string) {
  return { kind, label, updatedAt: new Date().toISOString() };
}